### ISSUE TITLE
VS 2022 support , module, form, widget

### ISSUE THREAD

**Issue by fasteddys** [Lombiq/Lombiq-Orchard-Visual-Studio-Extension#19]
Hello, can you please check the VS marketplace its not showing for VS 2022.

- [ ] Additionally, can you please add `a simple diagram` explaining how a the orchard module is composed, i.e. which parts go into making a module.
- [ ] Parts/Items/Types are very confusing.
- [ ] Lastly, you would get more traction from the developers if also help add `Generate Widget, Form`, option

**Comment by Piedone** [comment]
We're working on the VS 2022 upgrade: https://github.com/Lombiq/Lombiq-Orchard-Visual-Studio-Extension/pull/17

Your first and second points seem to be Orchard documentation issues, do I understand correctly? Note that this is the project just for the Lombiq Orchard Visual Studio Extension.

Can you elaborate on the third point, what do you mean, exactly, how do you imagine these working? Some wireframes to illustrate what you'd like to see, perhaps?

**Comment by fasteddys** [comment]
Thanks for the response, first let me say, we watched your videos and they are helpful in the class. There are also many gaps for the students, let me explain the confusion & request on the extension in two parts. It might help you better understand where we are coming from!

_Strategy to build components_: There's some other confusion, **Developers & students do not know**, _which path to take to build some business functionality_, for e.g. if a developer wants to create a `component `with a `master-details table for customer shipping/orders` tables Or, graph for `Number of returns per product graph, and a table below with details` on selected row-item in the graph... which one / do they use a module, do they use a widget, or content type its very fuzzy on which one to pick??

On the third part,  if developer wants to scaffold Orchard, Forms, or custom Widgets with your extension, for e.g. in the last .net dev meetup many mentioned, _they don't know how to create a pie chart for e.g. there are several use cases like a customer returns per product_.

I proposed using your Extension, they gave up first because of the compatibility issue. But also some functionality issue. So, if it has more comments/picture on what the code structure/components its scaffolding, step 1, 2 etc. in comments form then developers would be able to use it to easily create Module or Widget.

They _key_ thing to understand is `your extension is perhaps a good entry point as a visual tool in VS` to help them create the components they want. I am a lab assitant, Next semester there are 25 students who may pick Orchard CMS with your tool to build components in their lessons. Awareness is growing slowly!

**Comment by Piedone** [comment]
We appreciate the feedback though I still think that what you're talking about is best expressed as suggestions for the Orchard docs as issues under https://github.com/OrchardCMS/OrchardCore/issues. If you haven't done it already, I also encourage you to check out these resources:

- https://docs.orchardcore.net/en/latest/docs/glossary/ on the terminology and concepts.
- https://docs.orchardcore.net/en/latest/docs/reference/modules/Templates/ for code generation templates. We're intentionally not including such templates in this VS extension not to duplicate the built-in feature; in fact, we've removed templates because of this.
- https://orcharddojo.net/orchard-training/dojo-course-3-the-full-orchard-core-tutorial for a full Orchard tutorial and extensive, documented sample codes. In this, we also explain a lot of concepts and when to use each.

Out of curiosity, can you tell which meetup are you referring to, and at which institute are students learning about Orchard?
